In [ ]:
#create array of 10 zeroes
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#create array of 10 ones
arr= np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# create an array of 10 fives
arr1= arr * 5
arr1

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
#array of integers from 10 to 50
arr2 = np.arange(10,51)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
#create an array of all even integers from 1 to 50. use step size as the 3rd arg
arr3 = np.arange(10,51,2)
arr3

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
#create a 3x3 matrix with values ranging from 0 to 8
arr4 = np.arange(0,9).reshape(3,3)
arr4
#or 
arr5= np.arange(0,9)
arr5=arr5.reshape(3,3)
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#create a 3x3 identity matrix
arr6 = np.eye(3)
arr6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#use numpy to generate random no.s b/w 0 & 1
np.random.rand(1)

array([0.20933871])

In [ ]:
#use numpy to generate an array of 25 random no.s sampled from a normal distribution 
arr7=np.random.randn(25)
arr7

array([ 1.30784005, -0.80479361,  0.05147365, -0.71759276,  0.20757786,
        0.33288045,  0.30756331,  1.33941346,  0.24526996, -0.37245974,
       -1.7313692 , -0.7254039 , -1.05786672,  1.00954623,  0.13026728,
       -1.59772146, -0.27343984, -1.30141104, -0.37551099,  0.19566117,
       -1.43538214,  1.01924959,  0.7242615 ,  1.87591415, -2.02212048])

In [ ]:
arr8= np.arange(1,101)
arr8=(arr8/100)
arr8.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
#linearly spaced points b/w 0,1
arr9=np.linspace(0,1,20)
arr9

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
arr10=np.arange(1,26).reshape(5,5)
arr10

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arr10[2:,1:] #higher excluded

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
arr10[3,4]

20

In [ ]:
arr10[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [ ]:
arr10[4]

array([21, 22, 23, 24, 25])

In [ ]:
arr10[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])